const GET_CHARACTERS='GET_CHARACTERS';
const GET_STAFF='GET_STAFF';
const GET_STUDENTS='GET_STUDENTS';
const CHOOSE_HOUSE='CHOOSE_HOUSE';
const CHARACTERS_HOME='CHARACTERS_HOME';


module.exports={
    GET_CHARACTERS,
    GET_STAFF,
    GET_STUDENTS,
    CHOOSE_HOUSE,
    CHARACTERS_HOME
}